<a href="https://colab.research.google.com/github/sinyoung0110/DeepLearning/blob/main/week2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import tensorflow as tf

In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a=tf.placeholder(tf.float32, shape=[3])
b=tf.constant([5,5,5],tf.float32)

c=tf.add(a,b)

with tf.Session() as sess:
  print(sess.run(c,{a: [1,2,3]}))

[6. 7. 8.]


In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a=tf.placeholder(tf.float32)
b=tf.placeholder(tf.float32)

addOperation=tf.add(a,b)

init=tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(addOperation, {a:[1,2,3]})) #b를 안 씀

InvalidArgumentError: Graph execution error:

Detected at node 'Placeholder_18' defined at (most recent call last):
    File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    File "/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py", line 37, in <module>
    File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start
    File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start
    File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
    File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
    File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
    File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 685, in <lambda>
    File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 738, in _run_callback
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 825, in inner
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 361, in process_one
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request
    File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute
    File "/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
    File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    File "<ipython-input-14-f5a7d1e629dd>", line 5, in <cell line: 5>
Node: 'Placeholder_18'
You must feed a value for placeholder tensor 'Placeholder_18' with dtype float
	 [[{{node Placeholder_18}}]]

Original stack trace for 'Placeholder_18':
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
  File "/usr/local/lib/python3.10/dist-packages/colab_kernel_launcher.py", line 37, in <module>
  File "/usr/local/lib/python3.10/dist-packages/traitlets/config/application.py", line 992, in launch_instance
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelapp.py", line 619, in start
  File "/usr/local/lib/python3.10/dist-packages/tornado/platform/asyncio.py", line 195, in start
  File "/usr/lib/python3.10/asyncio/base_events.py", line 603, in run_forever
  File "/usr/lib/python3.10/asyncio/base_events.py", line 1909, in _run_once
  File "/usr/lib/python3.10/asyncio/events.py", line 80, in _run
  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 685, in <lambda>
  File "/usr/local/lib/python3.10/dist-packages/tornado/ioloop.py", line 738, in _run_callback
  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 825, in inner
  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 786, in run
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 361, in process_one
  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 261, in dispatch_shell
  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/kernelbase.py", line 539, in execute_request
  File "/usr/local/lib/python3.10/dist-packages/tornado/gen.py", line 234, in wrapper
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/ipkernel.py", line 302, in do_execute
  File "/usr/local/lib/python3.10/dist-packages/ipykernel/zmqshell.py", line 539, in run_cell
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 2975, in run_cell
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3030, in _run_cell
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/async_helpers.py", line 78, in _pseudo_sync_runner
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3257, in run_cell_async
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3473, in run_ast_nodes
  File "/usr/local/lib/python3.10/dist-packages/IPython/core/interactiveshell.py", line 3553, in run_code
  File "<ipython-input-14-f5a7d1e629dd>", line 5, in <cell line: 5>
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/array_ops.py", line 3274, in placeholder
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/ops/gen_array_ops.py", line 7073, in placeholder
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/op_def_library.py", line 796, in _apply_op_helper
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 2652, in _create_op_internal
  File "/usr/local/lib/python3.10/dist-packages/tensorflow/python/framework/ops.py", line 1160, in from_node_def


In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a=tf.placeholder(tf.int32)
b=tf.placeholder(tf.int32)

addOperation = tf.add(a,b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(addOperation, {a:[[1,2,3],[1,2,3],[1,2,3]],b:[[1,5,2],[1,2,3],[1,2,3]]}))


[[2 7 5]
 [2 4 6]
 [2 4 6]]


In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a=tf.placeholder(tf.float32)
b=tf.placeholder(tf.float32)

addOperation = tf.add(a,b)
minusOperation = tf.subtract(a, b)
mulOperation = tf.multiply(a, b)
divOperation = tf.divide(a, b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(addOperation, {a:[5,10,20],b:[2,5,5]}))
  print(sess.run(minusOperation, {a:[5,10,20],b:[2,5,5]}))
  print(sess.run(mulOperation, {a:[5,10,20],b:[2,5,5]}))
  print(sess.run(divOperation, {a:[5,10,20],b:[2,5,5]}))



[ 7. 15. 25.]
[ 3.  5. 15.]
[ 10.  50. 100.]
[2.5 2.  4. ]


In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

a=tf.placeholder(tf.float32)
b=tf.placeholder(tf.float32)

addOperation = tf.matmul(a,b)

init = tf.global_variables_initializer()

with tf.compat.v1.Session() as sess:
  sess.run(init)
  print(sess.run(addOperation, {a:[[1,2,3],[3,4,5],[1,1,1]],b:[[2,1],[1,2],[1,1]]}))

[[ 7.  8.]
 [15. 16.]
 [ 4.  4.]]


In [ ]:
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

x = tf.Variable(10, name="x")
y = tf.Variable(20, name="y")

z1 = tf.add(x, y, name="z1")
z2 = tf.multiply(x, y, name="z2")

z3 = tf.multiply(z1, z2, name="z3")

init = tf.global_variables_initializer()

with tf.Session() as sess:
    sess.run(init)
    y=tf.Variable(1) #선언은 session밖에 해야지 초기화할 때 살아남는다.
    writer = tf.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(z3))

writer.close()


6000
